---
extends: stylelint-config-standard
rules:
  block-no-empty:
  color-no-invalid-hex: true
  comment-empty-line-before:
    - always
    - ignore:
      - stylelint-commands
      - after-comment
  declaration-colon-space-after: always
  at-rule-no-unknown:
    ignore-at-rules:
      - extend
      - include
  indentation: null
  max-empty-lines: 2
  rule-empty-line-before:
  - always
  - except:
    - first-nested
    ignore:
    - after-comment
  unit-whitelist:
    - deg
    - em
    - px
    - rem
    - "%"
    - s
    - vh
