---
label: services
hide_body: false
fields:
- type: text
  label: layout
  name: layout
  default: service
  config:
    required: true
- type: text
  name: title
  label: title
  config:
    required: true
- type: textarea
  name: subtitle_1
  label: subtitle_1
  config:
    required: true
- type: textarea
  name: subtitle_2
  label: subtitle_2
- type: text
  name: cta_button_title
  label: cta_button_title
  config:
    required: true
- type: text
  name: service_title
  label: service_title
  config:
    required: true
- type: list
  name: service_bulletpoints
  label: service_bulletpoints
  config:
    use_select: false
    source:
      type: documents
- type: text
  name: time
  label: time
  config:
    required: true
- type: text
  name: cost
  label: cost
- type: textarea
  name: description
  label: description
  config:
    required: true
- type: text
  name: slug
  label: slug
- type: tag_list
  label: redirect_from
  name: redirect_from
- type: list
  name: bulletpoints
  label: bulletpoints
  config:
    use_select: false
    source:
      type: documents
- type: list
  name: projects
  label: projects
  description: Project slugs
  config:
    min: '1'
    use_select: false
    source:
      type: documents
pages:
- services/right-tech-stack-for-me.md
- services/resourcing-roadmaps-revenue.md
- services/solve-performance-problems.md
